### ISSUE TITLE
Fall through still sets status code when handleError: false

### ISSUE THREAD

**Issue by troykelly** [jfhbrook/node-ecstatic#222]
When config is set as `handleError: false` ecstatic is still setting the status code to 403 or 404 if there is no index or static file.
I would have expected that it would have left the status alone as `express.static` does.
Is there a way to truly not handle errors?

**Comment by jfhbrook** [comment]
Sounds like a bug. If you feel like investigating, ecstatic's source code isn't actually all that big and only a little hairy. If you send me a pull request I will merge.

**Comment by troykelly** [comment]
@jfhbrook It looks like it will be a fairly fundamental change.
Status is set during processing and passed on if handleError is false - It looks like it should be ignored throughout status-handlers - but that would be a major refactor.
I think this isn't so much a bug, it's just "expected behaviour"
My expectation of "handleError" was different to design.
The application does in fact not handle the error, but it does generate an error state.

**Comment by jfhbrook** [comment]
Hmmm

Yeah OK, I think I misunderstood the issue, it's been a minute since I've looked at this. It's coming back to me, though.

I think this issue is captured by https://github.com/jfhbrook/node-ecstatic/issues/154 and you're right, it's a pretty major refactor. Loosely related is https://github.com/jfhbrook/node-ecstatic/issues/183 , which would add restify support. My thinking here is to refactor to have a non-middleware API and then maybe a middleware-based adapter? But you're right, this is a bigger issue than I thought.

I'm gonna close this issue just cause I think #154 captures it pretty well, but if you disagree we can talk.
